apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  annotations:
    # spec.ingressClassName: alb
    # alb.ingress.kubernetes.io/scheme: internet-facing

    # # For WebSocket support
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
    # alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
spec:
  rules:
    # External rule for the frontend
    # - host: af5c43a6ad67d4f33b4a82c458084b43-947220440.us-east-1.elb.amazonaws.com
    # - host: frontend
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
                #   number: 3000

          # Backend service routes
          - path: /api/generate
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          # WebSocket path for backend
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8081

          # LLM service path
          - path: /llm
            pathType: Prefix
            backend:
              service:
                name: llm-service
                port:
                  number: 9093

          # Kafka service path (typically not exposed externally, but provided here if needed for testing)
          - path: /kafka
            pathType: Prefix
            backend:
              service:
                name: kafka-service
                port:
                  number: 9092

          # Zookeeper service path (typically internal, but included if needed)
          - path: /zookeeper
            pathType: Prefix
            backend:
              service:
                name: zookeeper
                port:
                  number: 2181
