apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 134428267718.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          ports:
            - containerPort: 3000
          resources:
            # requests:
            #   memory: '1Gi'
            #   cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '500m'
          env:
            - name: REACT_APP_WEBSOCKET_URL
              value: 'ws://backend:8081'
              # value: 'ws://aa67ee659414d41718e15e260bb162e6-1825036394.us-east-1.elb.amazonaws.com:8081'
              # value: 'wss://aa67ee659414d41718e15e260bb162e6-1825036394.us-east-1.elb.amazonaws.com/ws'
