# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ws-ingress
#   namespace: default
#   annotations:
#     networking.gke.io/managed-certificates: my-managed-cert
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: backend-ws-service
#                 port:
#                   number: 8081
